# Generated by Django 4.2 on 2023-04-15 18:09

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateField(auto_now=True, verbose_name='дата создания')),
                ('edit', models.DateField(auto_now_add=True, verbose_name='дата редактирования')),
                ('text', models.TextField(verbose_name='текст')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=100, unique=True, verbose_name='логин')),
                ('password', models.CharField(max_length=100, unique=True, verbose_name='пароль')),
                ('email', models.EmailField(max_length=254, verbose_name='почта')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='номер телефона')),
                ('date_of_birth', models.DateField(verbose_name='дата рождения')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateField(auto_now=True, verbose_name='дата создания')),
                ('edit', models.DateField(auto_now_add=True, verbose_name='дата редактирования')),
                ('title', models.CharField(max_length=100, verbose_name='заголовок')),
                ('text', models.TextField(verbose_name='текст')),
                ('image', models.ImageField(upload_to='image/', verbose_name='изображение')),
                ('author_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdPost.user', verbose_name='автор')),
                ('comments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdPost.comment', verbose_name='комментарии')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='author_comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdPost.user', verbose_name='автор'),
        ),
    ]
